-- 코드를 입력하세요
WITH TOTAL_USER AS (
    SELECT COUNT(DISTINCT USER_ID) AS Cnt FROM USER_INFO WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PURCHASED_USERS, (ROUND(COUNT(DISTINCT USER_ID)/(SELECT CNT FROM TOTAL_USER), 1)) AS PUCHASED_RATIO
FROM USER_INFO 
JOIN ONLINE_SALE 
USING (USER_ID)
WHERE (YEAR(JOINED) = 2021)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)